language: node_js
os: osx
node_js:
    -   "6"
before_script:
    -   brew install pandoc
    -   npm install
script:
    -   npm run --silent textlint
cache:
    directories:
        -   node_modules
