version: 2
jobs:
  build:
    docker:
      - image: ubuntu:17.10
    steps:
      - checkout
      - run:
          command: |
            apt update
            apt install -y latexmk make texlive texlive-latex-extra
      - run:
          command: latexmk
          working_directory: paper

