version: 2
jobs:
  build:
    docker:
      - image: paperist/alpine-texlive-ja
    steps:
      - checkout
      - run: apk add --no-cache ca-certificates
      - run: cp .latexmkrc ~/.latexmkrc
      - run:
          command: latexmk
          working_directory: paper
      - run: mkdir artifacts
      - run: cp paper/*.pdf artifacts/
      - store_artifacts:
          path: artifacts
      - persist_to_workspace:
          root: .
          path:
            - artifacts/

  upload:
    docker:
      - image: paperist/alpine-texlive-ja
    step:
      - checkout
      - attach_workspace:
          at: .
      - run: curl -F file=artifacts/*.pdf -F channels=#general -F token=${SLACK_BOT_API_TOKEN} https://slack.com/api/files.upload

workflows:
  version: 2
  build_and_upload:
    jobs:
      - build
      - upload:
          requires:
            - build
