version: 2
jobs:
  build:
    docker:
      - image: paperist/alpine-texlive-ja
    steps:
      - checkout
      - run: apk add --no-cache ca-certificates
      - run: cp .latexmkrc ~/.latexmkrc
      - run:
          command: latexmk
          working_directory: paper
      - run: mkdir artifacts
      - run: cp paper/*.pdf artifacts/
      - store_artifacts:
          path: artifacts

