version: 2
jobs:
  build:
    docker:
      - image: paperist/alpine-texlive-ja
    steps:
      - checkout
      - run: apk add --no-cache ca-certificates
      - run: cp .latexmkrc ~/.latexmkrc
      - run:
          command: latexmk
          working_directory: paper
      - run: mkdir artifacts
      - run: cp paper/*.pdf artifacts/
      - store_artifacts:
          path: artifacts
    textlint:
      working_directory: ~/project
      docker:
        - image: circleci/node:8
      steps:
        - checkout
        - restore_cache:
          key: dependency-{{ checksum "package.json" }}
          path: node_modules
        - run: npm install
        - save_cache:
          key: dependency-{{ checksum "package.json"}}
          path: node_modules
        - run: npm run --silent texlint-check --textpath paper/sample.tex

workflows:
  version: 2
  textlint-build:
    jobs:
      - textlint
      - build:
          requires:
            - textlint
