version: 2
jobs:
  textlint:
    working_directory: ~/project
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run: npm install
      - run: npm config set :texpath paper/sample.tex
      - run: npm run --silent textlint-check --textpath paper/sample.tex
  build:
    working_directory: ~/project
    docker:
      - image: paperist/alpine-texlive-ja
    steps:
      - checkout
      - run: apk add --no-cache ca-certificates
      - run: cp .latexmkrc ~/.latexmkrc
      - run:
          command: latexmk
          working_directory: paper
      - run: cp paper/*.pdf artifacts/
      - store_artifacts:
          path: artifacts

workflows:
  version: 2
  textlint-makepdf:
    jobs:
      - textlint
      - build:
          requires:
            - textlint
