version: 2
jobs:
  build:
    docker:
      - image: paperist/alpine-texlive-ja
    steps:
      - checkout
      - run: cp .latexmkrc ~/.latexmkrc
      - run:
          command: latexmk
          working_directory: paper
      - store_artifacts:
          path: paper

