version: 2
jobs:
  build:
    docker:
      - image: paperist/alpine-texlive-ja
    steps:
      - checkout
      - run:
          command: |
            apt update
            apt install -y latexmk make texlive-lang-japanese
      - run: cp .latexmkrc ~/.latexmkrc
      - run:
          command: latexmk
          working_directory: paper

