version: 2
jobs:
  build:
    docker:
      - image: paperist/alpine-texlive-ja
    steps:
      - checkout
      - run: apk add --no-cache ca-certificates
      - run: cp .latexmkrc ~/.latexmkrc
      - run:
          command: latexmk
          working_directory: paper
      - run: mkdir -p /tmp/artifacts
      - run: cp paper/*.pdf /tmp/artifacts/
      - store_artifacts:
          path: /tmp/artifacts
      - persist_to_workspace:
          root: /tmp/
          path:
            - /tmp/artifacts/

  upload:
    docker:
      - image: paperist/alpine-texlive-ja
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/artifacts
      - run: |
          for file in `\find . -maxdepth 1 -type f`; do
            echo $file
            curl -F file=$file -F channels=#general -F token=${SLACK_BOT_API_TOKEN} https://slack.com/api/files.upload
          done
workflows:
  version: 2
  build_and_upload:
    jobs:
      - build
      - upload:
          requires:
            - build
